import { classes, auras } from '../data/classes.js';
import { mageSkillTree } from '../data/talents.js';
import { skills } from '../data/skills.js';
import { buyMageUpgrade, buySpecUpgrade, countUpgrades, getMageLevel, getSpecLevel, selectSpecialization, resetMageUpgrades, resetSpecUpgrades, setSkillSlot, clearSkillSlot, selectAura } from '../systems/talents.js';
import { getDerivedStats, getSkillStats } from '../systems/stats.js';
import { saveGame } from '../systems/save.js';
import { getMapTier } from '../data/maps.js';

export function createRenderer(state){
 function log(message){state.logs.unshift(message);state.logs=state.logs.slice(0,8);}
 function renderHud(){
  const hud=document.getElementById('hud'),d=getDerivedStats(state),spec=state.selectedClass?`${classes[state.selectedClass].icon} ${classes[state.selectedClass].name}`:'Nenhuma';
  const slots=[0,1,2].map(i=>{const aura=i===2,id=aura?state.loadout.aura:state.loadout.skills[i],obj=id?(aura?auras[id]:skills[id]):null;return `<div class="hud-slot ${aura&&state.auraActive?'aura-on':''}"><b>${i+1}</b><span>${obj?obj.name:'Vazio'}</span><small>${aura&&obj?(state.auraActive?'ATIVA':'OFF'):''}</small></div>`}).join('');
  const w=state.wave;const prog=w.total?`${w.spawned}/${w.total}`:'0/0';
  hud.innerHTML=`<div class="panel-card stats-card"><div class="name">Mago <span>${spec}</span></div><div class="point-row"><span>⭐ Nível ${state.player.level}</span><span class="point mage-point">🔮 Mago <b>${state.mageSkillPoints}</b></span><span class="point spec-point">👑 Spec <b>${state.selectedClass?state.specSkillPoints:'—'}</b></span></div><div class="small">XP ${Math.round(state.player.xp)}/100 · 🗺️ <b>T${state.map.tier}</b> · 🌊 <b>Wave ${w.current}/10</b> · 👹 ${prog}${w.bossSpawned?' · 👑 BOSS':''}</div><div class="small">Poder Mágico <b>+${Math.round((d.spellPower-1)*100)}%</b> · Crítico ${Math.round(d.critChance*100)}%</div><div class="bar"><i class="hp" style="width:${state.player.hp/state.player.maxHp*100}%"></i></div><div class="bar"><i class="mp" style="width:${state.player.mp/state.player.maxMp*100}%"></i></div><div class="bar"><i class="xp" style="width:${state.player.xp}%"></i></div>${state.selectedClass==='thunder'?`<div class="small charge">⚡ Carga: ${Math.round(state.combat.charge)}%</div>`:''}<div class="hud-slots">${slots}</div></div>`;
 }
 function renderAim(){let aim=document.getElementById('aim-reticle');if(!aim){aim=document.createElement('div');aim.id='aim-reticle';document.getElementById('game').appendChild(aim);}aim.style.left=`${state.mouse.x}px`;aim.style.top=`${state.mouse.y}px`;aim.style.opacity=state.mouse.inside?'1':'.25';}
 function renderAura(){let ring=document.getElementById('aura-ring');if(!ring){ring=document.createElement('div');ring.id='aura-ring';document.getElementById('game').appendChild(ring);}const d=getDerivedStats(state),aura=state.loadout.aura?auras[state.loadout.aura]:null;if(!aura||!state.auraActive){ring.style.display='none';return;}ring.style.display='block';ring.style.left=`${state.player.x}px`;ring.style.top=`${state.player.y}px`;ring.style.width=`${d.auraRadius*2}px`;ring.style.height=`${d.auraRadius*2}px`;ring.style.borderColor=aura.color;ring.style.boxShadow=`0 0 24px ${aura.color}44,inset 0 0 22px ${aura.color}16`;}
 function renderArena(){const arena=document.getElementById('arena');arena.innerHTML='';state.enemies.forEach(e=>{const el=document.createElement('div');el.className=`enemy ${e.rarity||'normal'} ${e.boss?'boss':''} ${e.burning?'burning':''} ${e.markedUntil>performance.now()?'marked':''} ${e.stunnedUntil>performance.now()?'stunned':''}`;el.style.left=`${e.x}px`;el.style.top=`${e.y}px`;const title=e.boss?'👑 '+e.displayName:e.displayName;el.innerHTML=`<div class="enemy-label">${title}</div><div class="enemy-hp"><i style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></i></div>`;arena.appendChild(el)});const p=document.getElementById('player');p.style.left=`${state.player.x}px`;p.style.top=`${state.player.y}px`;document.getElementById('combat-log').innerHTML=state.logs.join('<br>');renderAim();renderAura();}
 function nodeButton(node,type){const core=node.core||false,current=type==='mage'?getMageLevel(state,node.id):getSpecLevel(state,node.id),maxed=current>=node.maxLevel;const b=document.createElement('button');b.className=`node ${current?'learned':''} ${maxed?'maxed':''} ${core?'core-node':''}`;b.innerHTML=`<div class="node-title"><b>${node.name}</b><span>${core?'ROOT':`${current}/${node.maxLevel}`}</span></div><small>${node.description}</small><div class="node-cost">${core?'NÚCLEO':maxed?'MAX':'▲ 1 ponto'}</div>`;b.onclick=e=>{e.preventDefault();const r=type==='mage'?buyMageUpgrade(state,node):buySpecUpgrade(state,node);log(r.ok?`✅ ${r.message}`:`⚠️ ${r.message}`);renderAll();};return b;}
 function renderClasses(){const root=document.getElementById('panel-classes');root.innerHTML=`<h2>👑 Especialização</h2><div class="sub">Uma única classe por personagem.</div><div id="class-grid" class="class-grid"></div><div id="spec-tree"></div><div class="map-panel"><div><b>🗺️ Mapa atual: T${state.map.tier}</b><small>As Waves servem como base para T1 → T20.</small></div><div class="map-actions"><button id="restart-tier">↻ Recomeçar T${state.map.tier}</button><button id="test-t2">▶ Testar T2</button></div></div>`;
  const grid=root.querySelector('#class-grid');Object.values(classes).forEach(cls=>{const chosen=state.selectedClass===cls.id,locked=Boolean(state.selectedClass)&&!chosen;const b=document.createElement('button');b.className=`class-button ${chosen?'selected':''} ${locked?'locked-class':''}`;b.disabled=locked;b.innerHTML=`<b>${cls.icon} ${cls.name}</b><span>${cls.description}</span><em>${chosen?'✓ Especialização ativa':locked?'🔒 Indisponível':'Escolher'}</em>`;b.onclick=()=>{const r=selectSpecialization(state,cls.id);log(r.ok?`👑 ${cls.name} escolhida.`:`⚠️ ${r.message}`);renderAll();};grid.appendChild(b);});
  const tree=root.querySelector('#spec-tree');if(!state.selectedClass){tree.innerHTML='<div class="empty-branch">Escolha uma especialização para liberar upgrades de Skills e Aura.</div>';}else{const cls=classes[state.selectedClass];tree.innerHTML=`<div class="tree-header"><div><b>${cls.icon} ${cls.name}</b><span>${state.specSkillPoints} ponto(s)</span></div><small>Todos os upgrades custam 1 ponto.</small></div><div class="skill-tree" id="spec-skill-tree"></div><h3>🌀 Aura</h3><div class="skill-tree" id="spec-aura-tree"></div>`;cls.skillNodes.forEach(n=>tree.querySelector('#spec-skill-tree').appendChild(nodeButton(n,'spec')));cls.auraNodes.forEach(n=>tree.querySelector('#spec-aura-tree').appendChild(nodeButton(n,'spec')));}}
  root.querySelector('#restart-tier').onclick=()=>{window.dispatchEvent(new CustomEvent('restart-tier'));};
  root.querySelector('#test-t2').onclick=()=>{window.dispatchEvent(new CustomEvent('test-tier',{detail:2}));};
 }
 function renderTalents(){document.getElementById('panel-talents').innerHTML=`<h2>🌳 Árvore de Skills do Mago</h2><div class="sub">Pressione <b>P</b> ou use o botão flutuante para abrir a árvore completa.</div><div class="tree-summary"><b>🔮 Pontos: ${state.mageSkillPoints}</b><span>${countUpgrades(state.mageUpgrades)} upgrades investidos</span></div><div class="actions"><button id="open-talents" class="action primary">Abrir árvore completa</button><button id="reset-mage" class="action">Reembolsar ${countUpgrades(state.mageUpgrades)} ponto(s)</button></div>`;document.getElementById('open-talents').onclick=()=>{state.talentsOpen=true;renderAll();};document.getElementById('reset-mage').onclick=()=>{const n=resetMageUpgrades(state);log(`↩️ ${n} ponto(s) de Mago devolvido(s).`);renderAll();};}
 function slotCard(index){const isAura=index===2,id=isAura?state.loadout.aura:state.loadout.skills[index],obj=isAura?(id?auras[id]:null):(id?skills[id]:null);return `<div class="loadout-slot ${isAura&&state.auraActive?'active':''}"><div class="slot-label">SLOT ${index+1} — ${isAura?'AURA':'SKILL'}</div><strong>${obj?obj.name:'Vazio'}</strong><small>${obj?obj.description||'':'Selecione uma opção abaixo.'}</small>${obj?`<button data-clear="${index}">Remover</button>`:''}</div>`;}
 function renderSkills(){const root=document.getElementById('panel-skills');root.innerHTML=`<h2>✨ Loadout</h2><div class="sub">2 skills da classe + 1 Aura. Todos os projéteis seguem o cursor.</div>${state.selectedClass?`<div class="loadout-grid">${slotCard(0)}${slotCard(1)}${slotCard(2)}</div><h3>⚔️ Skills</h3><div id="skill-options" class="option-grid"></div><h3>🌀 Auras</h3><div id="aura-options" class="option-grid"></div>`:'<div class="empty-branch">Escolha uma especialização primeiro.</div>'}<h3>✨ Ataque Básico</h3><div class="skill-card">${skills.basic.name} — Espaço · ${Math.round(getSkillStats(state,skills.basic).damage)} dano</div>`;if(!state.selectedClass)return;const cls=classes[state.selectedClass];for(const id of cls.skills){const s=skills[id],b=document.createElement('button');b.className=`option-button ${state.loadout.skills.includes(id)?'chosen':''}`;const st=getSkillStats(state,s);b.innerHTML=`<b>${s.name}</b><span>${s.description}</span><strong>⚔️ ${Math.round(st.damage)} dano · ${st.manaCost} Mana</strong><em>${state.loadout.skills[0]===id?'Slot 1':state.loadout.skills[1]===id?'Slot 2':'Selecionar'}</em>`;b.onclick=()=>{const target=state.loadout.skills[0]?1:0;setSkillSlot(state,target,id);renderAll();};root.querySelector('#skill-options').appendChild(b)}for(const id of cls.auras){const a=auras[id],b=document.createElement('button');b.className=`option-button ${state.loadout.aura===id?'chosen':''}`;b.innerHTML=`<b>${a.name}</b><span>${a.description}</span><em>${state.loadout.aura===id?'✓ Equipada':'Equipar'}</em>`;b.onclick=()=>{selectAura(state,id);renderAll();};root.querySelector('#aura-options').appendChild(b)}root.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.clear);if(i<2)clearSkillSlot(state,i);else{state.loadout.aura=null;state.auraActive=false;saveGame(state)}renderAll()});}
 function renderTalentModal(){let modal=document.getElementById('talent-modal');if(!state.talentsOpen){if(modal)modal.remove();return;}if(!modal){modal=document.createElement('div');modal.id='talent-modal';document.body.appendChild(modal);}modal.innerHTML=`<div class="talent-backdrop"></div><section class="talent-window"><header class="talent-top"><div><h1>🌳 Árvore de Skills — Mago</h1><p>Os troncos se ramificam para esquerda e direita. Para atravessar de um lado para o outro, você precisa comprar os nós intermediários.</p></div><div class="talent-points"><b>🔮 ${state.mageSkillPoints}</b><span>pontos disponíveis</span></div><button id="close-talents" class="close-talents">✕</button></header><div class="talent-legend"><span>🟢 Aprendido</span><span>🟣 Disponível</span><span>🔒 Bloqueado</span><span>💡 Cada nó = 1 ponto</span></div><div class="talent-canvas" id="talent-canvas"></div><footer><button id="reset-mage-modal" class="action">↩ Reembolsar árvore</button><span>Começar pela direita e alcançar a esquerda exige atravessar as pontes do centro.</span></footer></section>`;
  const canvas=modal.querySelector('#talent-canvas');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('tree-lines');svg.setAttribute('viewBox','0 0 1000 800');for(const n of mageSkillTree){for(const req of (n.requires??[])){const r=mageSkillTree.find(x=>x.id===req);if(!r)continue;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',r.x*10);line.setAttribute('y1',r.y*8);line.setAttribute('x2',n.x*10);line.setAttribute('y2',n.y*8);line.classList.add((getMageLevel(state,n.id)||n.core)?'line-active':'line');svg.appendChild(line);}}canvas.appendChild(svg);
  mageSkillTree.forEach(n=>{const b=nodeButton(n,'mage');b.style.left=`calc(${n.x}% - 74px)`;b.style.top=`calc(${n.y}% - 40px)`;if(n.requires?.length&&!n.core){const missing=n.requires.filter(id=>getMageLevel(state,id)<=0&&id!=='core');b.classList.toggle('path-locked',missing.length>0);}canvas.appendChild(b);});
  modal.querySelector('#close-talents').onclick=()=>{state.talentsOpen=false;renderAll();};modal.querySelector('.talent-backdrop').onclick=()=>{state.talentsOpen=false;renderAll();};modal.querySelector('#reset-mage-modal').onclick=()=>{const n=resetMageUpgrades(state);log(`↩️ ${n} ponto(s) devolvido(s).`);renderAll();};}
 function renderFrame(){renderHud();renderArena();if(state.talentsOpen){if(!document.getElementById('talent-modal'))renderTalentModal();}else if(document.getElementById('talent-modal'))document.getElementById('talent-modal').remove();}
 function renderAll(){renderHud();renderArena();renderClasses();renderTalents();renderSkills();renderTalentModal();if(!document.getElementById('talent-open-float')){const btn=document.createElement('button');btn.id='talent-open-float';btn.textContent='🌳 Árvore [P]';btn.onclick=()=>{state.talentsOpen=true;renderAll();};document.getElementById('game').appendChild(btn);}}
 return {renderAll,renderFrame,log};
}
